name: JavaScript CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18.x

jobs:
  javascript-ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/checkout@v4

      - run: yarn install
        working-directory: docsite
        name: Install Dependencies

      - run: yarn build
        working-directory: docsite
        name: Build Docsite