name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # This is important for poetry-dynamic-versioning

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
<<<<<<< HEAD
        python-version: '3.10'
=======
        python-version: '3.11'
>>>>>>> origin/main

    - name: Install dependencies
      run: |
        pip install venv
        poetry install

    - name: Build package
      run: poetry build

    - name: Publish to PyPI
      env:
        PYPI_USERNAME: __token__
        PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish
